-- setting
-- Generic key/value store for device/app settings. One row per setting.

CREATE TABLE IF NOT EXISTS setting (
  setting_id            INTEGER CONSTRAINT PK_setting PRIMARY KEY AUTOINCREMENT
  , setting_name        TEXT NOT NULL
  , setting_value       TEXT NOT NULL
  , setting_description TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS UN1_setting ON setting(setting_name);

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'db_type', '{"type":"production"}', 'type: "production" or "test" -- which physical database file the appdata.sqlite symlink points at, and so which one this row lives in. Set once, when that file is first created, and never changed afterward: production.sqlite always seeds as "production" via this default; scripts/switch-database.sh test overrides a freshly-created test.sqlite to "test" immediately after seeding it. Used as a pre-testing safety check (see Tests/CLAUDE.md) -- if this reads "production" during what is supposed to be a testing session, the appdata.sqlite symlink was never repointed at test.sqlite, and testing must not proceed.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'db_type');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'double_tap_settings', '{"enabled":false,"clickThreshold":90,"limit":20,"latency":50,"window":50}', 'Double-tap detection settings. enabled is what the app wants the gesture to be, and it is seeded off: the gesture pauses the cube on any knock hard enough, including one through the desk it is sitting on, so a cube nobody has asked for it should not be stopping the clock, and turning it off is faked: no BLE command disables double tap, so false means command 0x16 is sent with window forced to 0, which makes the gesture unrecognisable (Archive/Tests/Methods.md Method 22). The stored window keeps its real value throughout, since that is what turning the gesture back on sends. clickThreshold/limit/latency/window are the accelerometer parameters, seeded from DoubleTapParameters.default in Archive/TimeFlipApp/TimeFlipDoubleTapParameters.swift -- captured from a real device''s actual registers via Tests/Bench (see Tests/Bench/device_register_snapshot.json), not an arbitrary guess.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'double_tap_settings');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'led_settings', '{"brightness":50,"blink_interval":15}', 'LED settings: brightness (%, device cmd 0x09) and blink_interval (seconds, device cmd 0x0A) -- the only two LED properties the vendor protocol exposes (see docs/TimeFlip2 BLE Protocol v4.3.md), seeded from AppState''s ledBrightnessPercent/blinkIntervalSeconds defaults.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'led_settings');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'auto_pause_minutes', '{"minutes":0}', 'minutes: delay after which the device pauses itself if the face hasn''t changed (device cmd 0x05; 0 disables, matching the vendor protocol''s own disabled-by-default behavior; the device itself only supports whole-minute granularity, so this can''t be made finer). The timer resets every time the face changes.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'auto_pause_minutes');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'blip_time', '{"seconds":5}', 'seconds: while picking up and turning the device to find the desired face, it can pass over other faces briefly, creating unwanted entries for them. Any device_event segment shorter than this gets no time_entry and is marked processed instead; it is NOT merged into the following segment (that was specified once and dropped -- it needs a duration this data does not reliably have). 0 disables the filter. Edited on the App tab as "Ignore flips under", bounded 0-30 by TimeFlipConstants. Seeded to 5 to match the vendor spec, which is where the number comes from -- but note what that 5 actually governs: the spec says the 0x02 history stream carries "all intervals that lasted for at least 5 sec", and that is a property of THAT READ ONLY. The device stores short intervals and returns them to a single-event 0x01 read (confirmed on hardware, see the cheap single-frame refresh in HistoryIngestor), and they reach this app regardless via the live path -- each flip triggers a fetch that writes the current segment, and the next flip closes it out. 13 of 63 production segments were under 5s on 2026-08-02. This row was deleted once on the belief that the device already handled it; see docs/operation-spec.md.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'blip_time');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'firmware_check', '{"last_alert":"' || date('now', 'localtime') || '","interval_months":2}', 'last_alert (local date, YYYY-MM-DD) is when the firmware-update alert was last shown/acknowledged, seeded to the date this row was first inserted. interval_months is how many calendar months after last_alert before the user is prompted again to connect the device to the official TimeFlip app and check for a firmware update. The app does read the cube''s current version itself -- Firmware Revision String 0x2A26, kept in the device_info row -- so the reminder is not there for want of knowing which version is on the cube. What the app cannot do is change it: flashing new firmware is only possible from the vendor''s own app, and that is what this alert exists to send the user to. Knowing the version and being able to replace it are different things, and only the second one is missing. The Settings button that dismisses the alert resets last_alert to today regardless of whether the user actually checked, pushing the next alert out by interval_months either way.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'firmware_check');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'pause_on_lock', '{"enabled":true}', 'enabled: when true, locking the device from the app (command 0x04) pauses it first (command 0x06), so no time is recorded against a category while the device is locked and unattended. The lock drives the pause, not the other way round. Applies to both ways the app locks: the status item double-click gesture and quitting with this setting on (applicationShouldTerminate pauses, then locks). Unlocking does not auto-resume -- resuming is a separate decision by the user. Does not apply to a pause triggered by double-tapping the device itself; that never locks.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'pause_on_lock');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'fetch_history_interval_seconds', '{"seconds":10}', 'seconds: how often the app sends a history fetch request (command 0x02) to the device to pick up any entries not yet seen, in addition to the fetches already triggered by live face/pause events. Stored in seconds; a future Settings UI will expose this in minutes and convert it before saving here.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'fetch_history_interval_seconds');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'display_seconds', '{"enabled":true}', 'enabled: when true, the menu bar duration display includes a seconds component (H:MM:SS) and refreshes every second; when false, it shows H:MM and refreshes every minute.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'display_seconds');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'low_battery_level', '{"percent":10}', 'percent: battery_level (0-100, from the Battery Level characteristic 0x2A19) at or below which the device is considered low on battery and the menu bar activity text starts blinking red/white. Editable on the Device tab, which refuses 0 and caps the value at TimeFlipConstants.maxLowBatteryWarningPercent unless developer mode is on.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'low_battery_level');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'google_account', '{}', 'Cached identity of the connected Google account -- name and email from the OpenID Connect userinfo endpoint. Empty object until the first successful fetch after Google sign-in; populated once and then reused so the userinfo endpoint is not called again on every launch or Settings open (see GoogleOAuthClient). name and email are cleared on sign-out so a later sign-in with a different account re-fetches -- only those two, since the configuration keys below share this row and are not part of the identity. calendar_id and calendar_name are the calendar time entries sync into, kept here because a calendar selection is meaningless without an account. client_id is the OAuth client id, which is not a secret (it appears in every OAuth URL) and so lives here rather than in the Keychain alongside the client secret; in developer mode config.json overrides it at launch. All three are absent until set.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'google_account');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'debug', '{"enabled":false,"directory":"~/Library/Application Support/Facet"}', 'enabled: whether the debug trace is gathered at all -- the messages DebugLog.record prints to the terminal and writes as debug_log rows in debug.sqlite. Seeded off, so a fresh install is quiet until somebody turns it on to look into something. Live: read at launch and then told by the App tab Debug section as soon as the box is pressed, so logging starts and stops at that moment rather than at the next launch (DebugLog.setRecording). What makes leaving it off free is the message being an autoclosure, so a call site that is not being recorded builds no string at all. The trace database is brought up by the first message actually recorded, so a launch that records nothing leaves no debug.sqlite behind. A row edited behind the app back is not noticed until the next launch, which is why Tests/Scripted/00-setup.sh writes it with the app shut. It is the only gate there is: the compile-time developer flag this used to sit behind was removed on 2026-09-04. directory: which folder debug.sqlite is kept in. Not how a user finds it: the App tab Debug section reveals the file in the Finder and saves a copy of it to send in, so nobody navigates to this path. Seeded to the folder the app already keeps its databases in, deliberately away from ~/Documents and ~/Desktop, which are iCloud sync roots when Desktop and Documents syncing is on: a database written continuously inside one of those is how conflicted copies and corruption happen. Stored with a leading ~ and expanded where the file is opened (DebugTraceRules), never stored expanded: an absolute path names one machine, and this database is copied between machines and rebuilt from the DDL by the test suite. Read at launch, so a folder chosen on the App tab Debug section applies from the next launch, the trace database being open from launch to quit; a folder that cannot be written falls back to the seeded one and says so on stderr. What the file is called is not stored here: DatabaseBootstrap.debugDatabaseURL names it, so the folder is the only part anybody chooses. A to_file field sat beside these two, for writing the same messages to a plain log file; it was dropped on 2026-09-03, that being what debug.sqlite already is. An existing database may still hold that key, which nothing reads.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'debug');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'daily_reset_time', '{"hour":3,"minute":0}', 'hour (0-23) and minute (0-59), local time, at which each category''s tracked-time-vs-category.daily_limit accounting rolls over to a new day (default 3 AM, not midnight, so a session spanning midnight isn''t split). DayWindow turns this into the window DayTotal sums over, so it is also the window the menu bar''s over-limit colouring is judged against. Editable from the App tab, which steps it in whole hours plus AM/PM; the minute is stored as well so a finer time can be set when testing the rollover firing.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'daily_reset_time');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'connection', '{"connected":false,"last_connection":"' || strftime('%Y-%m-%dT%H:%M:%S', 'now', 'localtime') || '","connection_lost":"","quit_request":""}', 'Whether the app can reach its paired device right now, and when that last changed. Transient: every field here moves on each connect and drop, and none of it says anything about WHICH device is paired -- that is the paired / device_uuid rows. A connection is only possible while paired is true. connected: true between a successful login and the next drop or quit; this is the flag to read for "is the device reachable now?". The rest are local date-times (YYYY-MM-DDTHH:MM:SS) or empty. last_connection: the most recent successful device login -- written by DevicePairingRecorder() as part of every successful login (a new pairing, and each app-start/reconnect login; see DeviceLogin), seeded to when this row was created. connection_lost: when the app last detected a lost connection (recordConnectionLost, from handleDeviceDisconnect); cleared to "" on a clean quit so an intentional shutdown is not mistaken for a drop. quit_request: when the app was last asked to quit (recordQuitRequest, from applicationWillTerminate). Together these let a test or observer tell "connected now" from "lost the device" from "quit deliberately" rather than assuming.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'connection');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'paired', '{"paired":false}', 'Whether the app is paired to a device -- that is, whether it knows which device it is meant to talk to. Written by DevicePairingRecorder and read back through SettingStore. Durable: set true when a first pairing succeeds, and false ONLY when the user forgets the device (Forget Device, or the end of a confirmed factory reset; see DevicePairingRecorder). Losing the connection, going out of range, a rejected password and quitting all leave this true -- none of them change which device is paired, and clearing it here would make the app forget a perfectly good device the moment it went out of range. Seeded false, which is also the never-paired state. A test/observer reads this to decide whether the device needs pairing at all; for "is it reachable right now", read connection.connected. The peripheral uuid this pairing points at lives in device_uuid, and the name the cube is carrying in device_name.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'paired');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'device_uuid', '{}', 'uuid: the CoreBluetooth peripheral identifier of the device the app is paired to, used to reconnect to the same device rather than rediscovering it. Written by DevicePairingRecorder and read back through SettingStore. Durable alongside the paired row, changing only when the user pairs or forgets a device -- this row says which device, that one says whether. Seeded empty; it appears on first pairing and is cleared to null by Forget Device and by a confirmed factory reset. Note the identifier is assigned by this Mac''s CoreBluetooth stack, not by the device, so it is meaningless on any other machine and is not the same thing as the device''s BLE address.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'device_uuid');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'device_name', '{}', 'previous_name: the name this cube was called before the current one, absent until the first rename and updated only when the name actually changes (re-recording the same name on every connect must not push it out). It exists because the GAP name macOS reports is ONE CONNECTION STALE after a rename -- CBPeripheral.name is cached and re-read only on the next connect, measured over 120 polls in 30 seconds without changing (docs/timeflip2-firmware-observations.md) -- so the scan straight after a rename is still seeing the old name. Both names go into the eligible-device filter at startup, alongside the vendor default, so a rename cannot lose the cube at exactly the moment the user is watching for it. name: the name the cube itself is carrying -- its GAP Device Name (0x2A00), which is what device cmd 0x15 writes and what the scan sees. Read from the peripheral on every connect and mirrored here, so this follows the device rather than leading it. Written by DevicePairingRecorder(_:) and read back at launch by loadDeviceName(). Deliberately OUTLIVES Forget Device, unlike device_uuid: forgetting does not un-rename the cube, so this string stays the only way the filtered scan can find a device no longer answering to "timeflip". Cleared only by a confirmed factory reset (cmd 0xFF), which reverts the cube to the vendor name and so makes the remembered one wrong. Seeded empty; also empty before the first connection, since the name is read from the device and never guessed.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'device_name');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'device_info', '{}', 'What the paired cube says it is, read from the standard Device Information service (0x180A) on every successful login and mirrored here, so it follows the device rather than leading it. manufacturer (0x2A29), model (0x2A24), hardware (0x2A27) and firmware (0x2A26) are the four 20-byte read-only strings the vendor protocol lists in Tab. 1; System ID (0x2A23) is not read, nothing showing it. Each key is absent until a connection has actually answered for it, and a read that fails or comes back empty leaves the previous value alone rather than blanking it -- a cube that would not answer this time has not stopped being what it was. Written by DevicePairingRecorder.recordInfo and shown on the Device tab''s More rows, greyed while nothing is connected because a stored reading was true when it was taken and not necessarily now. Cleared by Forget Device along with paired and device_uuid (DevicePairingRecorder.recordForget), unlike device_name which deliberately survives one: because only what a cube answers is written, a second cube exposing no Device Information service would otherwise be shown wearing the first one''s manufacturer and firmware. Emptied to "" rather than removed, the key having to survive for the write''s read-back to confirm it. Display is gated separately and does not depend on the clear: DeviceInfoRules.detail shows "Not paired" over whatever is stored whenever paired is false.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'device_info');

INSERT INTO setting (setting_name, setting_value, setting_description)
SELECT 'time_entry_check', '{"last_check":"' || strftime('%Y-%m-%dT%H:%M:%S', 'now', 'localtime') || '"}', 'last_check (local date-time, YYYY-MM-DDTHH:MM:SS) is when the app last swept device_event for segments to turn into time_entry rows, seeded to when this row was created so the first sweep has a starting point rather than a null. A segment is eligible when finalised = 1, paused = 0, processed = 0, and its device_event_id is not already in time_entry -- that last condition is guaranteed by UN1_time_entry rather than merely checked, so a double sweep cannot double-count. See docs/operation-spec.md § 3, and note that a segment shorter than blip_time is merged into the following one instead of becoming its own entry, so an eligible segment does not always produce a row.'
WHERE NOT EXISTS (SELECT 1 FROM setting WHERE setting_name = 'time_entry_check');
